Changed zoneId to zone_id
smar000/evohome-Listener pull request #19
Opened 2020-10-15 16:48 UTC by number42net

I ran into some issues running both the 2.0.0 and master branches, mainly caused by part of the code expecting the devices dict to contain zoneId and other parts expecting zone_id. Initially I started fixing these by using the dict.get() method, but that was causing the zones to just turn to 0.

This was causing errors like these:

```
2020-10-15 14:13:13 |     | ERROR               | ''zoneId'' on line 725 [Command ZONE_TEMPERATURE, data: '---  I --- 01:180412 --:------ 01:180412 30C9 021 0007C901085402078A030BF804073D05073E0608BB', port: 1]
Traceback (most recent call last):
  File "evogateway.py", line 725, in process_received_message
    COMMANDS[msg.command_code](msg)
  File "evogateway.py", line 875, in zone_temperature
    zone_id = devices[msg.source_id]["zoneId"]
KeyError: 'zoneId'
```

Second minor issue is that the BDR91 is being recognized as a controller instead of a relay, presumably because it's often used as a on/off boiler controller.

2020-10-15 17:00 UTC, number42net commented
Also added a fix to automatically resubscribe on reconnect as requested in issue #17

2020-10-16 07:04 UTC, smar000 commented
Thanks @number42net - much appreciated! I will have a quick look through both the commits later in the day before merging.

2020-10-16 08:00 UTC, smar000 commented
Just had a quick look but am not sure about the "zoneId" change, as this is the key used in the `devices.json` file, whereas `zone_id` is the python variable used internally within the script. Could you post an extract from your `devices.json` file, to confirm that you are using the same key in your json file.

The use of both `zoneId`/`zone_id` is a bit messy TBH, and sort of evolved from the early days. It is quite possible that there are bugs related to this, but I've been using the script as is for many months and haven't noticed any errors.

If I recall correctly, the `devices` holds the the `devices.json` directly, and so will use "zoneId" as its key (assuming that there has been no change in the `devices.json` file as compared to the sample). Once loaded, all internal collections, such as `zones` should use the `zone_id` for their key. The proper way to get consistency would be to change the key in `devices.json`, but given that it is a breaking change for other users, I've been putting it off. May have to look at it now if it is throwing errors for you all.

2020-10-16 08:06 UTC, smar000 requested changes
`device["zoneId"]` is correct and should remain as is, assuming the `devices.json` file device key format has not been changed. Similarly for `devices[d]["zoneId"]` etc.

Can you pls double check your `devices.json` file.

Thanks.

2020-10-16 08:12 UTC, smar000 submitted a review, later dismissed

2020-10-16 08:17 UTC, smar000 reviewed
Could you do the mqtt change as a separate PR, so that I can merge it by itself. Many thanks.

2020-10-16 08:44 UTC, smar000 commented on evogateway.py
> -      device_type = "CONTROLLER"
This is correct as a _controller_ I think. Pls see https://github.com/domoticz/domoticz/blob/851da37f7abb99d0a6060945a48ebd49772f57cc/hardware/EvohomeRadio.cpp#L1759

2020-10-17 07:07 UTC, number42net commented
Here is a copy of my devices.json:

```{
    "01:180412": {
        "name": "Touch screen",
        "zoneMaster": false,
        "zone_id": 7
    },
    "04:092733": {
        "name": "Bed1",
        "zoneMaster": false,
        "zone_id": 3
    },
    "04:092745": {
        "name": "Office",
        "zoneMaster": false,
        "zone_id": 4
    },
    "04:019193": {
        "name": "Bed2",
        "zoneMaster": false,
        "zone_id": 6
    },
    "04:092747": {
        "name": "Living room",
        "zoneMaster": false,
        "zone_id": 1
    },
    "13:163331": {
        "name": "Underfloor relay",
        "zoneMaster": false,
        "zone_id": 7
    },
    "10:137422":{
        "name": "Boiler",
        "zone_id": -1,
        "zoneMaster": false
    },
    "04:092741": {
        "name": "Bed3",
        "zoneMaster": false,
        "zone_id": 2
    },
    "04:092739": {
        "name": "Wardrobe",
        "zoneMaster": false,
        "zone_id": 5
    },
    "18:056026": {
        "name": "EvoGateway",
        "zoneMaster": true,
        "zone_id": 240
    },
    "04:092763": {
        "name": "Faulty",
        "zoneMaster": false,
        "zone_id": -1
    }
}
```

After going a bit more through the code I realise that probably the problem came from devices.json and devices_new.json using a different tag. My workflow was to let the script discover all my new devices and then just copy and paste the content from devices_new.json into devices.json. And then start making alterations to the names and zone IDs. 

It would be great if you could use the same key in both files like I did in my commit, it doesn't really matter which it is, I can just change my devices.json to match.

As for the controller vs relay, if that's what most other apps expect then I'll just have to live with it as well 🙂

2020-10-17 19:49 UTC, number42net commented
I've added two more commits:

The first changes datetime.now() to datetime.utcnow() when publshing time stampts to MQTT. There is a hardcodes Z at the end of the ISO time string, which implies UTC time. But now() returns local time. I ran into this while writing a client that writes the values from MQTT into InfluxDB.

The second is a follow up on issue #17. While restarting my own MQTT broker I noticed that the issue is not just that the subscriptions are not renewed on reconnect, but that there is not attempt to reconnect at all. I found that this is because there is a on_disconnect handler. After removing this handler the script automatically reconnects as expected.

2020-10-17 21:45 UTC, smar000 commented
> After going a bit more through the code I realise that probably the problem came from devices.json and devices_new.json using a different tag. My workflow was to let the script discover all my new devices and then just copy and paste the content from devices_new.json into devices.json. And then start making alterations to the names and zone IDs.
> 
> It would be great if you could use the same key in both files like I did in my commit, it doesn't really matter which it is, I can just change my devices.json to match.

Thanks for spotting this. On looking back through the evolution of the code, I can see that the key "zone_id" crept in into the automatically detected new devices file when I did some refactoring some months back (it was originally "zoneId", and consistent with the sample `devices.json` file). The cleanest option is that we keep "zoneId" in the json files and correct the bug introduced in the line writing new devices to file. 

I will push an update tomorrow for this.

2020-10-17 21:46 UTC, smar000 commented
> I've added two more commits:
> 
> The first changes datetime.now() to datetime.utcnow() when publshing time stampts to MQTT. There is a hardcodes Z at the end of the ISO time string, which implies UTC time. But now() returns local time. I ran into this while writing a client that writes the values from MQTT into InfluxDB.
> 
> The second is a follow up on issue #17. While restarting my own MQTT broker I noticed that the issue is not just that the subscriptions are not renewed on reconnect, but that there is not attempt to reconnect at all. I found that this is because there is a on_disconnect handler. After removing this handler the script automatically reconnects as expected.

Great, thanks for both of these! I will get them merged tomorrow as well after brief testing.

2020-10-18 11:31 UTC, smar000 commented
The mqtt reconnect and datetime commits have been merged. The "zoneId" matter was addressed separately by correcting the typo in the write line to the `devices_new.json` file.

2020-10-18 11:31 UTC, closed without merging